name: PR Versioning & Tagging

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - qa
      - main

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch all tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest version
        id: get_version
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Determine bump type from PR title
        id: bump_type
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "PR Title: $title"

          if [[ "$title" =~ [Mm]ajor ]]; then
            bump="major"
          elif [[ "$title" =~ [Mm]inor ]]; then
            bump="minor"
          elif [[ "$title" =~ [Pp]atch ]]; then
            bump="patch"
          elif [[ "$title" =~ [Pp]rod ]]; then
            bump="patch"
          else
            echo "❌ PR title must include major/minor/patch/prod"
            exit 1
          fi

          echo "bump=$bump" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          latest="${{ steps.get_version.outputs.latest }}"
          bump="${{ steps.bump_type.outputs.bump }}"
          base_branch="${{ github.base_ref }}"

          # strip pre-release suffix if present
          core_version=$(echo "$latest" | cut -d'-' -f1)

          IFS='.' read -r major minor patch <<< "$core_version"

          if [ "$bump" = "major" ]; then
            major=$((major+1)); minor=0; patch=0
          elif [ "$bump" = "minor" ]; then
            minor=$((minor+1)); patch=0
          elif [ "$bump" = "patch" ]; then
            patch=$((patch+1))
          fi

          new_version="$major.$minor.$patch"

          # Decide pre-release type based on branch
          if [ "$base_branch" = "dev" ]; then
            pre="alpha"
          elif [ "$base_branch" = "qa" ]; then
            pre="beta"
          else
            pre=""
          fi

          # Handle prerelease numbering
          if [ -n "$pre" ]; then
            count=$(git tag --list "${new_version}-${pre}.*" | wc -l)
            count=$((count+1))
            new_version="${new_version}-${pre}.${count}"
          fi

          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "✅ New version: $new_version"

      - name: Create Git Tag
        run: |
          new_version="${{ steps.bump_version.outputs.new_version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "$new_version" -m "Release $new_version"
          git push origin "$new_version"
